version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" 
  order-service:
    build: ./order-service
    #image: order-service:latest
    container_name: order-service
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/orderdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
 